// Import the createSlice function from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the slice
const initialState = {
  mode: "dark", // Default mode is "dark"
  userId: "63701cc1f03239b7f700000e", // Example user ID
};

// Create a slice of the Redux state named "global"
export const globalSlice = createSlice({
  name: "global", // Name of the slice
  initialState, // Initial state defined above
  reducers: {
    // Define a reducer function to toggle the mode between "light" and "dark"
    setMode: (state) => {
      // If current mode is "light", change it to "dark"; otherwise, change it to "light"
      state.mode = state.mode === "light" ? "dark" : "light";
    },
  },
});

// Export the action created by the slice, so it can be dispatched to change the mode
export const { setMode } = globalSlice.actions;

// Export the reducer function generated by createSlice
// This will be used in the store configuration
export default globalSlice.reducer;
